package das.omegaterapia.visits.preferences

import android.content.Context
import android.graphics.Bitmap
import androidx.datastore.core.DataStore
import androidx.datastore.preferences.core.Preferences
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.stringPreferencesKey
import androidx.datastore.preferences.preferencesDataStore
import dagger.hilt.android.qualifiers.ApplicationContext
import das.omegaterapia.visits.model.entities.AuthUser
import das.omegaterapia.visits.utils.APIClient
import das.omegaterapia.visits.utils.CipherUtil
import das.omegaterapia.visits.utils.TemporalConverter
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import java.util.*
import javax.inject.Inject
import javax.inject.Singleton


/*******************************************************************************
 ****                Application Settings & User Preferences                ****
 *******************************************************************************/


/*************************************************
 **             Data Store Instance             **
 *************************************************/
private val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = "PREFERENCES_SETTINGS")


/*************************************************
 **           Data Store Key Provider           **
 *************************************************/

// Singleton class used to get correct and predefined Data Store Keys.
@Suppress("FunctionName")
private object PreferencesKeys {
    val LAST_LOGGED_USER = stringPreferencesKey("last_logged_user")

    // Dynamic keys depending on the current user
    fun USER_LANG(user: String) = stringPreferencesKey("${user}_lang")
    fun USER_DAY_CONVERTER(user: String) = stringPreferencesKey("${user}_day_converter")
    fun USER_MULTIPLE_DAY_CONVERTER(user: String) = stringPreferencesKey("${user}_multiple_day_converter")
}


/*************************************************
 **         User Preferences Repository         **
 *************************************************/

/**
 * Class implementing a repository pattern. It provides access to app's settings and user preferences.
 *
 * It is annotated with Hilt's @Singleton so there's only one instance created on the application.
 * This class instance is created automatically by Hilt (Hilt also injects the required [Context])
 *
 * @property context Any context (required to get DataStore instance)
 */

@Singleton
class PreferencesRepository @Inject constructor(
    @ApplicationContext private val context: Context,
    private val cipher: CipherUtil,
    private val apiClient: APIClient,
) : ILoginSettings, IUserPreferences {


    companion object {
        private const val CIPHER_KEY = "last_logged_auth_user"
    }

    private lateinit var profileImage: Bitmap


    /*------------------------------------------------
    |                Last User Logged                |
    ------------------------------------------------*/
    // This "setting" is used for biometric authentication.

    /**
     * Collects the first preference item generated by DataStores [Flow] and returns the last logged user.
     */
    override suspend fun getLastLoggedUser(): AuthUser? {
        val encryptedData = context.dataStore.data.first()[PreferencesKeys.LAST_LOGGED_USER]

        return try {
            if (encryptedData != null) {
                val data = cipher.decryptData(CIPHER_KEY, encryptedData)
                Json.decodeFromString(data)
            } else null
        } catch (e: IllegalArgumentException) {
            e.printStackTrace()
            null
        }
    }

    // Set the last logged user on DataStore Preferences
    override suspend fun setLastLoggedUser(user: AuthUser) {
        context.dataStore.edit { preferences ->
            preferences[PreferencesKeys.LAST_LOGGED_USER] = cipher.encryptData(CIPHER_KEY, Json.encodeToString(user))
        }
    }


    /*------------------------------------------------
    |                User Preferences                |
    ------------------------------------------------*/
    /*
     * Curren user's username is required in these methods below.
     *
     * All getters returns a kotlin Flow in order to get automatic updates on the settings.
     * The Preferences flow is mapped to get only the desired preference or the default value if null.
     *
     * Getters are suspended to not block Main (UI) thread.
     */

    //----------   Language Preference   -----------//
    override fun userLanguage(user: String): Flow<String> =
        context.dataStore.data.map { it[PreferencesKeys.USER_LANG(user)] ?: Locale.getDefault().language }

    override suspend fun setUserLanguage(user: String, langCode: String) {
        context.dataStore.edit { preferences ->
            preferences[PreferencesKeys.USER_LANG(user)] = langCode
        }
    }


    //------   One-Day Converter Preference   ------//
    override fun userDayConverter(user: String): Flow<String> =
        context.dataStore.data.map { it[PreferencesKeys.USER_DAY_CONVERTER(user)] ?: TemporalConverter.oneDayDefault.name }

    override suspend fun setUserDayConverter(user: String, converter: String) {
        context.dataStore.edit { preferences ->
            preferences[PreferencesKeys.USER_DAY_CONVERTER(user)] = converter
        }
    }


    override fun userMultipleDayConverter(user: String): Flow<String> =
        context.dataStore.data.map { it[PreferencesKeys.USER_MULTIPLE_DAY_CONVERTER(user)] ?: TemporalConverter.multipleDayDefault.name }

    override suspend fun setUserMultipleDayConverter(user: String, converter: String) {
        context.dataStore.edit { preferences ->
            preferences[PreferencesKeys.USER_MULTIPLE_DAY_CONVERTER(user)] = converter
        }
    }

    //TODO Documentar
    override suspend fun userProfileImage(): Bitmap {
        if (!this::profileImage.isInitialized) {
            profileImage = apiClient.getUserProfile()
        }
        return profileImage
    }

    override suspend fun setUserProfileImage(image: Bitmap) {
        profileImage = image
        apiClient.uploadUserProfile(image)
    }
}